services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: eventsdb
      POSTGRES_USER: secretuser
      POSTGRES_PASSWORD: verystrongpassword
    ports:
      - '5432:5432'
  events:
    image: event-registration:0.0.1-SNAPSHOT
    depends_on:
      - mongo
      - postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - '8080:8080'