services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: eventsdb
      POSTGRES_USER: secretuser
      POSTGRES_PASSWORD: verystrongpassword
    ports:
      - '5432:5432'
