spring:
  application:
    name: event-registration
  datasource:
    url: jdbc:postgresql://localhost:5432/eventsdb
    username: secretuser
    password: verystrongpassword
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always