create table attendees (id integer generated by default as identity, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id));
create table events (end_date date, id integer generated by default as identity, organizer_id integer not null, start_date date, venue_id integer not null, name varchar(255) not null, primary key (id));
create table organizers (id integer generated by default as identity, description varchar(255), name varchar(255) not null, primary key (id));
create table products (event_id integer not null, id integer generated by default as identity, price numeric(38,2) not null, description varchar(255), name varchar(255) not null, primary key (id));
create table registrations (attendee_id integer not null, id integer generated by default as identity, product_id integer not null, ticket_code varchar(255), primary key (id));
create table venues (id integer generated by default as identity, city varchar(255), country varchar(255), name varchar(255) not null, street varchar(255), primary key (id));
alter table if exists events add constraint FKmied7el0kcl27ul1mn6384hki foreign key (organizer_id) references organizers;
alter table if exists events add constraint FKqdxygdernwwt74hdvix9u5nr3 foreign key (venue_id) references venues;
alter table if exists registrations add constraint FK9rg8nfrv7ocm12dmieqel8gkv foreign key (attendee_id) references attendees;
